
public enum GOAP_STATE
{
  HAS_LAUNCHER,
  HAS_MATTER,
  LAUNCHER_IS_FACING_AT_TARGET,
  LAUNCH_BOMBARDMENT_COMPLETE,
  LAUNCH_BOMBARDMENT_SCOUTING,
  LAUNCH_BOMBARDMENT_PROBING,
  LAUNCH_BOMBARDMENT_DEFENSIVE,
  LAUNCH_BOMBARDMENT_CORE,
  LAUNCH_BOMBARDMENT_IN_DIRECTION,
}
